Add Contact form to mobile version
richy4dev/Personal-Portfolio pull request #4
Opened 2022-07-14 19:50 UTC by richy4dev

In this branch, i and my team added a contact form section according to required design.
Requirements:
Name field accepts up to 30 chars.
Email field accepts only emails.
Message field accepts up to 500 chars.
All fields have placeholder text.
All fields have the correct type.
Collect data by using the [Formspree service](https://formspree.io/html).
In order to lay out the elements on the page you should use Flexbox.
You don't need to implement any functionality that requires JavaScript.
You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
Implement the button interactions (enable, hover, etc.).

2022-07-14 20:20 UTC, Nemwel-Boniface requested changes
## Hello @richy4dev           :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Good job styling your footer section it looks really good :clap:
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 20:20 UTC, Nemwel-Boniface commented on Index.html
> +          </p>
- [ ] Great job styling and adding some animations for this section. However, the paragraph is not well positioned. KIndly position it at the center so that it can match the chosen [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

**This is how your design currently looks like:**

![image](https://user-images.githubusercontent.com/86318284/179074533-aa749c0d-aa46-48f6-92bf-22f138e19ea0.png)

**This is the desired Figma design:**

![image](https://user-images.githubusercontent.com/86318284/179074651-c2c0c492-c8ee-482c-9aa6-3c67f43de10e.png)

2022-07-14 20:20 UTC, Nemwel-Boniface commented on Index.html
> +      </form>
- [ ] You have done a tremendous job styling the form and making sure that it sends the form data correctly. Kindly make sure that you keep to the chosen [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1), this way your project will look more professional.

**This is how your design currently looks like:**

![image](https://user-images.githubusercontent.com/86318284/179075224-8c3b0bdb-86fe-4700-95d2-4b9b100232e1.png)

**This is the desired Figma design:**

![image](https://user-images.githubusercontent.com/86318284/179075340-7825545e-6b77-41a1-bca0-8eadc248cdf1.png)

2022-07-14 20:20 UTC, Nemwel-Boniface commented on Index.html
> +            </button>
- [ ] You have done a good job adding interactions for your buttons. Kindly make sure that you add the correct button interactions eg on hover, on focus. Below is how the button interactions should look like:

![image](https://user-images.githubusercontent.com/86318284/179075796-f5687c9b-41a1-4632-a7bb-fa040644a68c.png)

2022-07-15 09:11 UTC, sumairq approved these changes
### Hi @richy4dev  , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Design matches figma template
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 09:17 UTC, merged